# pragma: allowlist secret
version: "3.9"
services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOSTNAME=postgres # Use 'postgres' instead of 127.0.0.1
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY_FASTAPI_AUTH=d58d44eb67a3087ef343aee359062ea975b4984a52ed88ea58686f27ce28a524
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - fastapi_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16
    container_name: fastapi_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

volumes:
  postgres_data:

networks:
  fastapi_network:
    driver: bridge
